default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kopool_development
  username: kopool
  password: sixstair

test:
  <<: *default
  database: kopool_test
  username: kopool
  password: sixstair

production:
  <<: *default
  database: kopool_production
  username: kopool
  password: <%= ENV['KOPOOL_DATABASE_PASSWORD'] %>
